variables:
  ENV: "development"
  LC_ALL: "C"

default:
  image: python:3.13
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install .[dev]

stages:
  - lint
  - test

lint-job:
  stage: lint
  script:
    - mypy
    - black . --check
    - flake8

unit-test-job:
  stage: test
  script:
    - pytest
