repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/johann-petrak/licenseheaders
    rev: "v0.8.8"
    hooks:
      - id: licenseheaders
        types: ["python"]
        args:
          - "-E"
          - ".py"
          - "-t"
          - "./scripts/apache-2.tmpl"
          - "-o"
          - "Direction générale de la prévention des risques (DGPR)"
          - "-cy"
          - "-n"
          - "OCAPI"
          - "-u"
          - "https://github.com/mte-dgpr/ocapi"
          - "-f"

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --ignore-init-module-imports

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear>=24.4.0
          - flake8-isort>=6.1.0

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml", "--no-warn-unused-ignores"]
        additional_dependencies:
          - pydantic>=2.8
          - pydantic-settings>=2.0
          - pytest>=8.3.0
          - arretify~=0.2.0
          - beautifulsoup4>=4.12
          - types-beautifulsoup4
          - networkx>=3.2
          - langchain-core>=0.2.0
          - types-requests
        files: "^ocapi/"

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        additional_dependencies:
          - pytest>=8.3.0
          - pytest-cov>=5.0.0
          - arretify~=0.2.0
          - beautifulsoup4>=4.12
          - langchain-core>=0.2.0
          - networkx>=3.2
          - pydantic>=2.8
          - pydantic-settings>=2.0
          - requests>=2.31
          - roman>=4.2
        pass_filenames: false
        stages: [pre-commit]
