[project]
name = "package_name"
version = "0.1.0"
description = ""
requires-python = ">=3.10"
authors = []
license = { text = "" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = [
  "pytest",
  "mypy",
  "black",
  "pre-commit",
  "flake8",
  "flake8-bugbear",
  "flake8-isort",
  "autoflake",
  "isort",
]

[project.scripts]
# "package-cli" = "package_name.module:main"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
packages=["package_name"]
plugins = ["pydantic.mypy"]
follow_untyped_imports = true
exclude = ["venv", "tmp"]
