name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

env:
  ENV: development
  LC_ALL: C

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    container: python:3.12
    strategy:
      matrix:
        name: [unit-tests, lint]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        run: |
          pip install --upgrade pip
          pip install .[dev]

      - name: Run unit tests
        if: matrix.name == 'unit-tests'
        run: pytest

      - name: Run linters
        if: matrix.name == 'lint'
        run: |
          mypy
          black . --check
